require("plugins")
require("general_config")
require("mason_setup")
require("completions")
-- require("statusline_evil_lualine") use statusline_evil_lualine for evil lualine or statusline_cosmicink for cosmicink
require("statusline_cosmicink")
-- require("statusline_slanted_gaps")
-- require("statusline_bubbles")
require("filetree")
require("keybinds")
require("tabline_config")
require("themery_config")
require("terminal")
require("telescope_config")
require("comment_config")
require("noice_config")
require("conform_config")
